TOPLEVEL_LANG ?= verilog # language of the design (verilog, vhdl, etc.)

VERILOG_SOURCES += design.sv # list of verilog source files, including the top level module

COCOTB_TOPLEVEL = tanh_lut # name of the top level module

COCOTB_TEST_MODULES = testbench # name of the python test file without the .py extension

include $(shell cocotb-config --makefiles)/Makefile.sim